services:
 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weatherapp
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata:
 