export const strConstants = {
  emptyStr: '',
  less: 'less',
  spaceStr: ' ',
  usersName: 'users name',
  username: 'username',
  logOut: 'Log out',
  signIn: 'Sign in',
  email: 'email',
  password: 'password',
  loadingLong: 'Loading ...',
  warning: 'warning',
  error: 'error',
  info: 'info',
  success: 'success',
}