export const strConstants: {
  currentPassword: 'current-password',
  none: 'none',
  emailAddress: 'email-address',
  default: 'default',
  center: 'center',
  [index: string]: string | { [index: string]: string },
} = {
  alphabet: {
    a: 'a',
  },
  emptyStr: '',
  less: 'less',
  spaceStr: ' ',
  usersName: 'users name',
  username: 'username',
  logOut: 'Log out',
  signIn: 'Sign in',
  email: 'email',
  password: 'password',
  loadingLong: 'Loading ...',
  warning: 'warning',
  error: 'error',
  info: 'info',
  success: 'success',
  number: 'number',
  underlineStr: '_',
  degreesMeasure: '°',
  degreesCelsiusMeasure: '°C',
  speedWindMeasure: ' metre/sec',
  pressureMeasure: ' hPa',
  humidityMeasure: '%',
  waterMeasure: ' mm',
  percentage: '%',
  sunrise: 'sunrise',
  sunset: 'sunset',
  tempDay: 'temp_day',
  tempMin: 'temp_min',
  tempMax: 'temp_max',
  tempNight: 'temp_night',
  tempEve: 'temp_eve',
  tempMorn: 'temp_morn',
  feelsLikeDay: 'feels_like_day',
  feelsLikeNight: 'feels_like_night',
  feelsLikeEve: 'feels_like_eve',
  feelsLikeMorn: 'feelsLikeMorn',
  pressure: 'pressure',
  humidity: 'humidity',
  windSpeed: 'wind_speed',
  windDeg: 'wind_deg',
  rain: 'rain',
  snow: 'snow',
  date: 'date',
  slash: '/',
  currentPassword: 'current-password',
  none: 'none',
  emailAddress: 'email-address',
  default: 'default',
  center: 'center',
}